DoSomething/longshot

app/database/seeds/DatabaseSeeder.php

This was causing the seed to fail

Added missing semi-colon.

---

app/models/Winner.php
app/views/pages/partials/_winners-gallery.blade.php

Update particpation in winners template

---

app/controllers/StatusController.php
app/views/status/index.blade.php

Conditionally include & print timeline.

---

app/controllers/RegistrationController.php
app/database/seeds/RolesTableSeeder.php

Remove the applicant user role.

---

app/controllers/ProfilesController.php
app/models/Profile.php
app/views/profile/partials/_form_profile.blade.php

Use a mutator to save birthdate.

---

app/routes.php
app/views/admin/applications/index.blade.php
app/views/admin/winners/index.blade.php

- added link to update user info from the winners index page
- updated route name to reflect it's in the admin group
- removed winner description text from table, it's not helpful

Update winner admin

---

app/models/Export.php
app/views/admin/reports/export.blade.php

Created another export, requested recs, not complete.

---

app/views/profile/partials/_form_profile.blade.php

Fixes #643 
@weerd super quick one for ya

Removed the high from the schools.

---

app/controllers/admin/AdminController.php

Update admin queries to search for non-admins.

---

app/controllers/admin/AdminController.php

Right, join where there is no row in role table.

---

app/database/migrations/2015_04_29_101023_remove_app_roles.php

If the applicant role exists, remove it & all users with that role

---

app/controllers/PagesController.php
app/controllers/WinnerController.php
app/controllers/admin/AdminController.php
app/models/Application.php
app/models/Scholarship.php
app/models/Winner.php
app/views/admin/applications/show.blade.php
app/views/pages/partials/_winners-gallery.blade.php

This PR adds some additional logic to show a "Revoke Scholarship" button to an applicant that has been awarded a scholarship. It provides an interface for removing the winner status in case it was done in error or needs to be removed for some other reason.
This PR also updates the logic for the Scholarship Class period to correctly reflect the class period for the gallery being displayed.
@angaither 
CC: @mikefantini @lizzydivine 
Note: Once deployed it would be useful to do a cache clear on the site.

Winner designation updates

---

wercker.yml

Added composer self-update

---

readme.md

@angaither @weerd 
I made some updates to the set up readme. See my changes below.

Update readme to clarify some setup instructions.

---

app/Scholarship/Composers/PageComposer.php
app/Scholarship/Repositories/SettingRepository.php
app/controllers/admin/ScholarshipController.php

Adds redirect so you don't go to a blank page on Scholarship creation and also does some cleanup.
@sbsmith86 @angaither

Updates to redirect to listing after scholarship creation.

---

app/database/migrations/2015_08_26_130610_add_additional_fields_to_winners_table.php

This PR adds a new migration which updates the Winners table and adds the new columns to hold all winners data.
---
@angaither @sbsmith86

Migration  to add new fields to the winners table.

---

app/models/Export.php
app/views/admin/reports/export.blade.php

Addresses #665 
This PR adds additional data export options to the export page in the app. The options added are outlined in #665. I will be exporting these as CSVs to close out that issue, but wanted to get some eyes on the queries and code to make sure everything looks accurate.

Additional data export options

---

app/views/application/partials/_form_application.blade.php

fixed issue #691 
Changed previous text for GPA box to the new one: GPA (please enter your GPA on a 4.0 or 5.0 scale)

GPA Help Text

---

app/controllers/ApplicationController.php
app/database/migrations/2015_09_22_111649_allow_test_type_null.php
app/models/Application.php
app/views/application/partials/_form_application.blade.php

fixes issue #698 
-allows test_type to be null when the user chooses not to submit scores
-test_score is also null if left blank
-otherwise, the type and score are passed to the database

test_type dropdown updates

---

app/views/layouts/partials/_form-password-field.blade.php

fixes issue #293 and ONLY issue #293

password placeholder

---

app/controllers/admin/AdminController.php

after voting admins are now redirected to the page they were on

---

default.env.local.php

fixes issue #671
changed the mandrill dummy key value so you can set up the app

fixes mandrill api dummy key

---

app/views/admin/recommendations/edit.blade.php

fixes issue #711 so admins can now edit all fields of a recommendation

fix edit recs page for admins, allow to edit last name and email

---

app/views/status/review.blade.php

fixes #718 
displays everything except for scholarship id

when applicants review their application, do not display the scholarship id to them

---

app/controllers/admin/AdminController.php
app/models/Profile.php
app/views/admin/applications/show.blade.php

fixes #721 
edit the admin controller to only attempt to access information if it has been submitted, only display information in the view that has been submitted

only display profile and application information that has been submitted

---

app/models/Export.php

fixes #724 
add rec link, applicant first and last name to csv for rec requested not finished

add rec link to csv for rec requested not finished

---

app/views/admin/applications/show.blade.php

so that you will see the partial profile if an app doesn't exist instead of seeing an error

add else if to only show button if an app exists

---

app/models/Export.php
app/views/admin/reports/export.blade.php

fixes #730 
-replaces newlines and tabs with " " and commas with semicolons in the activities

export csv of applicants marked yes

---

default.env.local.php

I think this is what StyleCI was complaining about

add missing comma

---

app/Http/Controllers/RegistrationController.php
app/Http/Controllers/StatusController.php
app/Http/routes.php
app/Scholarship/Forms/RegistrationForm.php
resources/views/registration/edit.blade.php
resources/views/status/index.blade.php

- added necessary routes, views, and controller methods
- we now pass the user to the status view in order to link to the account edit view
- triggers new email if user changes their email
Fixes #743

allow users to edit their own account information

---

app/Http/Controllers/ApplicationController.php
app/Http/Controllers/ProfilesController.php
app/Http/Controllers/RecommendationController.php
app/Http/Controllers/admin/AdminController.php
resources/views/admin/applications/show.blade.php

- when an admin edits an application (or profile or recommendation), when they hit update they return to the app show page
- when an admin marks an app as complete, they return to the app show page
- other clean-ups (seem to be things leftover from L5 update)
Fixes #746

Admin edit applicant redirect

---

app/Http/Controllers/ApplicationController.php
app/Http/Controllers/RecommendationController.php
app/Http/Controllers/admin/AdminController.php
app/Http/routes.php
resources/views/admin/applications/show.blade.php

- create new route and form button to call new `resendRecEmail` function in `AdminController.php`
- `resendRecEmail` function is essentially the same as [`prepareRecRequestEmail`](https://github.com/DoSomething/longshot/blob/admin-re-send-rec/app/Http/Controllers/RecommendationController.php#L251-L260) in `RecommendationController.php`
Fixes #749

allow admins to resend rec emails

---

app/Http/Controllers/ApplicationController.php
app/Http/Controllers/StatusController.php
app/models/Application.php

- just indentation changes in `ApplicationController.php`
- added new helper function to `StatusController.php` to check the submitted GPA and rate the app as `no` if it is below the minimum
- I decided to make `checkGPA` a separate function to follow the same thing we did with [`confirmationEmail()`](https://github.com/DoSomething/longshot/blob/95daa9e7d39e95aa0f5b5a81021ae24394aaf6f5/app/Http/Controllers/StatusController.php#L172-L176)
Fixes #756

when app submitted, check gpa and rate "no" if too low

---

app/models/Email.php
database/migrations/2016_04_19_201256_add_email_from_address_to_scholarship.php
database/migrations/2016_04_19_201548_add_email_from_name_to_scholarship.php
resources/views/admin/scholarship/partials/_form_scholarship.blade.php

- Let admins set the sent from email and name
- There might be something in [`mail.php`](https://github.com/DoSomething/longshot/blob/master/config/mail.php) that we need to overwrite ([this if anything I think](https://github.com/DoSomething/longshot/blob/master/config/mail.php#L83)), but I'm not sure. I will need to be able to send a test email and see what it looks like
Fixes #751

let admins alter from email and from email name

---

tests/TestCase.php

Just like the one [here](https://github.com/DoSomething/gladiator/blob/f8d8ef3d3a76240c500f05079a4fdc5507b15b30/tests/TestCase.php)

make TestCase.php look just like the one in gladiator

---

wercker.yml

The `Copy in any other files in your project` step was not fully completed it turns out

this file never got pulled over during upgrade

---

composer.json
tests/RegistrationTest.php
tests/TestCase.php

- added packages needed for testing (to use mockery)
- create test for creating an account
- add mock method to TestCase (which all other test files extend)

Registration test

---

readme.md

This accidentally got removed during the upgrade. A couple of changes need to be made but I want to bring it back first.

bring back setup instructions

---

.env.example
app/Http/Controllers/RegistrationController.php
app/models/Email.php
config/deploy.rb
database/migrations/2014_09_24_190609_update_label_fields.php
database/migrations/2014_09_26_182048_update_rank_fields.php
database/migrations/2014_10_02_135113_update-status-on-app.php
database/migrations/2014_10_09_130928_update-participation-field-to-longtext.php
database/migrations/2014_10_14_120211_remove-empty-rec-rows.php
database/migrations/2014_11_04_100223_update_winner_desc_field.php
database/migrations/2014_11_04_155303_update_profile_add_index_to_user_id.php
database/migrations/2014_12_04_142631_update_zipcode_from_int_to_varchar.php
database/migrations/2015_04_29_101023_remove_app_roles.php
database/seeds/ScholarshipsTableSeeder.php
phpunit.xml
tests/RegistrationTest.php
tests/TestCase.php
wercker.yml

- add missing config items for wercker
- add missing down functions for migrations
- make `key` and `recipient` fillable on emails
- create an email in the registration test

Fix wercker tests

---

.env.example
app/Http/Controllers/ApplicationController.php
app/Http/Controllers/SessionsController.php
app/Http/Controllers/UploadController.php
app/Http/Controllers/WinnerController.php
app/Http/Controllers/admin/AdminController.php
app/Http/Kernel.php
app/Http/Middleware/CheckIfAdmin.php
app/Http/routes.php
app/models/Application.php
database/migrations/2016_04_14_162511_rename_link_column.php
gulpfile.js
resources/assets/less/admin.less
resources/views/admin/applications/show.blade.php
resources/views/admin/layouts/master.blade.php
resources/views/application/create.blade.php
resources/views/application/edit.blade.php
resources/views/application/partials/_form_application.blade.php

- new route to limit access to uploaded images to admins and the user that uploaded them
- add file saving and deleting functionality to application controller
- change database column to upload from link
- add validation to make sure file is an image
- some of the style elements weren't being built properly
For review: @angaither and @DFurnes for the 🎨 
Fixes #748

Add applicant image upload and surrounding fixes

---

resources/assets/less/bootstrap.less
resources/views/admin/applications/show.blade.php

- add class to `bootstrap.less` to let us make the background of the voting div white
- add data-spy affix to fix the position of the voting buttons when scrolling, so it's always visible
- it looks like this:
Fixes #747

voting always visible when admin views app

---

app/Http/Controllers/admin/SettingsController.php
app/Scholarship/Repositories/SettingRepository.php
database/seeds/SettingsTableSeeder.php
resources/views/admin/settings/partials/_form_settings.blade.php
resources/views/layouts/master.blade.php

- added new setting to upload a background image
- admins can also remove the image if they no longer wish to have a background image and just want the grey
- takes pngs and jpegs

let admins add a background to site

---

app/Http/Controllers/EmailController.php
app/Http/Controllers/admin/AdminController.php
app/Http/routes.php
app/models/Email.php
database/seeds/EmailsTableSeeder.php
resources/views/admin/reports/export.blade.php
resources/views/admin/settings/emails/edit.blade.php
resources/views/layouts/master.blade.php

- need to add more tokens for other things they want to access, but I think this is working otherwise!
- added new route and buttons for sending emails
- new function on `AdminController` to send emails to groups and deal with token stuff
- cleaned up the way we were exporting csvs
- switched up the way we dealt with tokens in `Emails.php`
Fixes #757

add group email functionality

---

Gemfile
Gemfile.lock

- copied these over just like they were before the upgrade to L5.2

bring back the two gem files

---

Capfile

add capfile

---

config/deploy.rb

Updating the cap commands in deploy.rb to create the correct symlinks for Laravel 5. The .env file's name has changed, and the location of some of the public files and logs has changed.

Updating deploy.rb for Laravel 5

---

app/Http/Controllers/PagesController.php
resources/views/pages/partials/_block_cta.blade.php

- use functions on the actual scholarship object that we passed through

there was another spot the scholarship wasn't being accessed properly

---

resources/views/admin/applications/show.blade.php

- only show the voting div if this person can be voted on
- formatting changes elsewhere

when the voting div migrated the if was left behind

---

resources/views/layouts/master.blade.php
resources/views/pages/partials/_block_cta.blade.php
resources/views/pages/partials/_block_default.blade.php
resources/views/pages/partials/_block_detailed-list.blade.php
resources/views/pages/partials/_block_introduction.blade.php
resources/views/pages/partials/_block_steps.blade.php
resources/views/pages/partials/_block_timeline.blade.php
resources/views/pages/partials/_winners-gallery.blade.php

- switched a bunch of `{{ stuff }}` to `{!! stuff !!}`

hopefully stopping all the html tags from showing up

---

.env.example
config/mail.php

- need to set a global from address for emails

add a dummy email

---

app/Http/Controllers/admin/AdminController.php

- this Request::get should have been changed to $request->input

request input instead of get

---

resources/views/application/create.blade.php
resources/views/application/edit.blade.php
resources/views/profile/create.blade.php
resources/views/profile/edit.blade.php
resources/views/recommendation/applicant_edit.blade.php
resources/views/recommendation/create.blade.php
resources/views/recommendation/edit.blade.php
resources/views/registration/create.blade.php

I'm not sure why this renders fine locally, but this should kill those html tags in the wild.

more {{ to {!!

---

config/services.php

- definitely need this here
- hopefully this is the final piece!

email config in services.php

---

app/Http/Controllers/Auth/PasswordController.php
app/Http/Controllers/PagesController.php
app/Http/routes.php
resources/views/auth/emails/password.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/sessions/create.blade.php

- use the new `PasswordController` and such instead of the old `RemindersController`
- new views associated with the new controllers

Password reset

---

app/Http/Controllers/ApplicationController.php
app/Http/Controllers/RecommendationController.php
app/Http/Controllers/StatusController.php
app/models/Application.php
app/models/Recommendation.php
resources/views/status/index.blade.php

- added a new checkbox to the status page to show whether or not the app has been submitted
- part of the `store` function in `ApplicationController` disappeared, now we are actually saving all the pieces
- In the `RecommendationController` we were marking apps as completed when they had one rec completed, regardless of how many recs were required. Now we check if they have the minimum number before marking them as completed
- Somewhat related to that, the `StatusController` was doing some real complicated stuff to decide if the app was completed, now we just straight up use `isComplete`
Fixes #811
Fixes #810

new checkbox + fixin up some logic

---

issue_template.md
pull_request_template.md

add templates for issues and PRs

---

resources/views/layouts/master.blade.php

- we want both! this way we don't get errors if someone only fills in one

make sure we have a kit id and font name

---

app/Http/Controllers/admin/AdminController.php

- colons need to be added around the token before it is passed to `sendEmail`
Fixes #814

add the colons in the AdminController

---

app/Http/Controllers/ProfilesController.php
app/Http/Controllers/admin/AdminController.php
resources/views/profile/partials/_form_profile.blade.php

- The code to update the race on a profile was pretty confusing and there was some incorrect logic in there somewhere, but it was hard to find the error (as in I didn't find it). I ended up quasi re-writing these chunks which needed to happen anyway, but everything seems to work now and is easier for me to wrap my head around.
- As an applicant, try a couple passes of switching around which checkboxes are checked on your profile. Hit "Save as Draft" after each pass and make sure it updated correctly. Do the same thing from the admin side as well. 
- One of the tests caught an error!!! 🎉 
Fixes #815
Fixes #822

the whole race checkbox situation

---

database/seeds/AppSubmitHelpTextTableSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/EmailsTableSeeder.php
database/seeds/FaviconSettingsTableSeeder.php
database/seeds/HelperTextTableSeeder.php
database/seeds/InteractionColorSettingsTableSeeder.php
database/seeds/NominateSettingsTableSeeder.php
database/seeds/OfficialRulesSettingsTableSeeder.php
database/seeds/OpenGraphDataSettingsTableSeeder.php
database/seeds/PagesTableSeeder.php
database/seeds/PreviousWinnersTableSeeder.php
database/seeds/RolesTableSeeder.php
database/seeds/ScholarshipsTableSeeder.php
database/seeds/SettingsTableSeeder.php
database/seeds/SiteInfoSettingsTableSeeder.php
database/seeds/StatusPageHelpTextTableSeeder.php
database/seeds/TrackingCodeSettingTableSeeder.php
database/seeds/UsersTableSeeder.php
database/seeds/WaterGateSeeder.php

- Most importantly it passes StyleCI. 
- It also calls all of our seeds from `DatabaseSeeder.php` which is a thing that we need now. 
- Includes a bunch of `use` statements inside the seeds themselves
Run `php artisan db:seed` and make sure it doesn't crash and seeds as expected.
Refs #813 (once we run `db:seed` on whitelabel that issue should be fixed)

call seed files correctly

---

resources/views/pages/static.blade.php

Makes it so that no plain old HTML shows up on static pages.
👀  should do it!
Fixes #830

another {{ that needed to be changed to {!!

---

resources/views/layouts/master.blade.php

I don't know why all of the things like this work locally, they shouldn't! Another HTML situation.
👓

properly escape the html around the font code

---

app/models/Setting.php
database/migrations/2016_09_15_193019_add_new_settings_and_emails.php

All this info was in seed files before, but we don't want to re-seed apps in prod because we will lose all current settings, etc.
Make sure this won't break everything.

update migrations so we don't have to re-seed apps in prod

---

.gitignore
composer.lock

Don't ignore `composer.lock`.
Is `composer.lock` there?

don't ignore composer.lock

---

config/deploy.rb

Adds the symlink for content/images
Updating Laravel to the newest version requires moving around the symlinks so that uploaded images persist and are linked properly.

Adding symlink for content/images

---

config/deploy.rb

Fixes the images symlink
Fixes #

Fixing symlink

---

config/deploy.rb

Adds a symlink from the shared pages folder to the public pages folder. 
Fixes #

Adding symlink for pages folder

---

config/deploy.rb

Adds a symlink from `shared/app/uploads` to `storage/app/uploads`
This branch has been deployed to, and is working on Whitelabel

Adding app/uploads symlink"

---

resources/views/registration/create.blade.php

Let us use markdown in the create account description.
use ur 👀 
Fixes #850

allow us to use markdown here

---

app/Http/Controllers/ApplicationController.php

Requires the applicant to include a test score if they chose a test type. Test score is not required if they chose "Prefer not to submit scores."
Make sure you cannot submit with a test type and blank test score. Make sure you can submit with "Prefer not to submit scores" and blank test score.
Historical note: my initial work on this was my first ever PR 🎉 
Fixes #698 (again)

test score is required if you choose a test type

---

app/models/Email.php

Replaces tokens in email subjects as well as the bodies. 
Make sure tokens work in email subjects as well as bodies.
When I re-worked this I should have done it for subjects too! Never came up in testing because I didn't realize I had missed it/that it was supposed to work 😬

replace tokens in email subject too

---

app/Http/Controllers/RecommendationController.php
resources/views/recommendation/applicant_edit.blade.php
resources/views/recommendation/create.blade.php
resources/views/recommendation/edit.blade.php

- add "(no dashes)" to the text of the phone number field on all the rec forms (which is consistent with what we have elsewhere)
- when requesting recs for the first time, we validate the first form and any others that are filled in. Previously, it was just any forms that are filled in, which meant that an applicant could submit a blank form and get the message "Your request has been submitted"
Is this the best way to handle a fully blank form being submitted?
@ngjo is a grrrreat tester!!!!

a few more rec fixes

---

app/Http/Controllers/NominationController.php

There's no `get` route on nominations which leads me to believe that the button disable situation will take care of the issues with this. We don't want to add any new routes I don't think so we'll see if that takes care of it an re-assess if necessary.
👀

no new routes

---

app/Http/Middleware/CheckIfAppSubmitted.php

We don't use the redirect facade elsewhere so let's not do that here.
👀

don't use the redirect facade for consistency

---

app/Http/Controllers/RecommendationController.php

Correctly grab the token to resend the rec request email when the applicant updates the recommender's email address.
Can this break everything? 
Fixes #864

get first from collection, then get token from that

---

resources/views/pages/partials/_nomination-form.blade.php

You can use HTML in the nomination text now!
Toss some HTML in "Nominate Text" at `admin/settings/general` and make sure it formats correctly.
Fixes #867

fix display of nominate text

---

resources/views/layouts/master.blade.php

revert commit made to master
:eye: 
Fixes #
This reverts commit ee243465ced4e111b136a0e5639a42a11fbda653.

Revert "added optimizely origin master script to header"

---

.env.example
wercker.yml

What's this PR do?
I've updated the wercker.yml to use the ds-docker-php box as a build box to support the migration into the new world of Wercker deploys. I've also reverted the Capistrano deploys to work with Wercker.
How should this be manually tested?
Check Wercker to make sure the build and deploy works. https://app.wercker.com/dosomething/longshot/runs

Wercker docker

---

config/deploy.rb
wercker.yml

This adds in the gateway info so that Wercker can connect to servers inside of private subnets.
https://app.wercker.com/dosomething/longshot/runs/Whitelabel/59a46aca3b92d9000174297f
For some reason this didn't get added back to the wercker.yml when we upgraded to building on Docker
- [ x ] Tested on Whitelabel.

Adding gateway for deploys

---

.env.example
wercker.yml

Laravel requires a 32 character app key now. I copied [what was done in Northstar in this PR](https://github.com/DoSomething/northstar/pull/576) to generate an app key.
Did I copy Northstar right?
Was getting this on whitelabel:

Copying what they did in Northstar

---

app/Http/Controllers/ApplicationController.php

Fixes an error where you get this
```
Undefined variable: image_uploads (View: /var/www/scholarship-application-app/releases/20170831175637/resources/views/application/partials/_form_application.blade.php) (View: /var/www/scholarship-application-app/releases/20170831175637/resources/views/application/partials/_form_application.blade.php)
```
when trying to edit an application.
It's because I didn't apply the changes that I made in my previous PR to the application create to the application edit.
👀 
Oops!

Fix error on edit application page

---

resources/views/admin/index.blade.php

Updates copy to be less ambiguous.
Does the new copy (above or in the actual files) match Jen's changes below?
[Pivotal](https://www.pivotaltracker.com/story/show/152475433)

Make /admin page clearer

---

app/Exceptions/Handler.php
wercker.yml

On Longshot we tend to get a bunch of `TokenMismatchException`s (I'm guessing from people leaving the tab open and their session timing out?), so let's silence these because they are not errors we need to worry about. They are handled gracefully and do not necessarily indicate a problem.
👀 Will this break everything?
[Card](https://www.pivotaltracker.com/story/show/153639571)

Silence TokenMismatches

---

resources/views/admin/scholarship/partials/_form_scholarship.blade.php
resources/views/application/partials/_form_application.blade.php

Updates language on admin scholarship creation/editing form to let them know that the extra questions will live right below the test score question.
Updates the user application form to put the extra questions right below the test score question.
Are the extra questions where I said they'd be?
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/150050426)

Move extra questions to just below test score

---

resources/assets/js/confirm.js
resources/assets/js/main.js
resources/views/admin/layouts/master.blade.php
resources/views/admin/reports/export.blade.php

Now when admins are sending an email to a group, they get prompted to confirm that they actually wish to send an email to that particular group.
Does this only send the email if the admin confirms?
[Card](https://www.pivotaltracker.com/story/show/154001260)

Confirmation message for group emails

---

app/Console/Commands/GenerateTestData.php

Use the versions of the factories that we are expecting.
👀 
I made a mistake!
[Card](https://www.pivotaltracker.com/story/show/154258102)

Quick fix to use the right versions of the factories

---

app/Http/Controllers/admin/AdminController.php

1. Adds headers to all CSV downloads
2. Uses Laravel's `response()->download` so that we can hopefully get more information if something goes wrong
3. Logs the content of the CSV file (for now)
Is this a reasonable way to add the headers?
We needed to add headers and sometimes the downloads do not work and we are trying to get more context.
[Card 1](https://www.pivotaltracker.com/story/show/151860768)
[Card 2](https://www.pivotaltracker.com/story/show/152934047)

Add headers and try to make downloads more debuggable

---

resources/views/status/index.blade.php
resources/views/status/review.blade.php

Fix the help text on the "Review & Submit" page and the "Status" page so that they will render with proper markdown.
👀 
Flagged prior to Footlocker Internal Launch.
[Card](https://www.pivotaltracker.com/story/show/155269413)

Fix markdown for a couple of helper texts

---

app/models/Recommendation.php
package-lock.json
resources/views/admin/applications/show.blade.php

Adds recommendation link above "Resend Email To Recommender" button on application page. 
When you go to the application page and scroll down to the "Recommender Responses" section, each recommendation should have a "Recommendation Link" that links to the recommendation form.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/158995352) Pivotal Card.

Adds recommendation link above Resend Email To Recommender button

---

app/Http/Controllers/ApplicationController.php
app/models/Application.php
resources/views/application/partials/_form_application.blade.php

Requires the "How did you hear about this scholarship?" question for all apps. 
Make sure if a selection besides "Please Select" is not selected, an error message saying "You must pick an option from the drop down list." appears.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/151859376) Pivotal Card.

Requires "How did you hear about this scholarship?" Question 

---

resources/views/registration/create.blade.php

- Updates copy from "Yes, I'm eligible" to "Yes, I'm eligible and I agree to this use of my contact info"
Is this okay? (styles aren't rendering 100% correctly locally so ignore the Times New Roman)
[Card](https://www.pivotaltracker.com/story/show/160322054)

Update account creation eligibility checkbox for GDPR

---

resources/views/admin/layouts/partials/footer.blade.php
resources/views/layouts/partials/footer.blade.php
resources/views/layouts/partials/header.blade.php
resources/views/status/review.blade.php

There were some hardcoded text references to TMI, this switches those to DoSomething Strategic.
👀 and did I miss any?
[Card](https://www.pivotaltracker.com/story/show/160360034)

Switch hardcoded references to TMI to DoSomething Strategic

---

Procfile
composer.json
composer.lock
config/queue.php
nginx.conf
package-lock.json
package.json
public/.user.ini

This pull request adds a procfile & build scripts for Heroku, and the library & configuration settings so we can use SQS as a queue driver on Heroku.
👀 
Nah.

Configure Longshot to run on Heroku.

---

composer.lock

This pull request updates dependencies, and locks the change made in #921.
👀 
References [this Slack conversations](https://dosomething.slack.com/archives/C03T8SDMW/p1543341929032200).

Update dependencies & lock gd extension.

---

Procfile

- Once we get a bunch of users some of the group email jobs can get hefty and timeout!
👀 
[Slack thread](https://dosomething.slack.com/archives/C03T8SDMW/p1544206180000100)
🤠

Up timeout for queue processing to 240 seconds

---

app/Http/Controllers/ApplicationController.php

Whoops! Another `$user` that was undefined in this controller.
Follow-up from #929 & too little testing. 🙃 
🐎 
N/A

Whoops, another undefined $user.

---

config/auth.php

🛳 When you get emailed a password reset link, it will work for one day instead of one hour.
👀 
It's all in the card!
[Card](https://www.pivotaltracker.com/story/show/162774826)

Increase password reset token expiration to one day (from one hour)
