app/commands/TransferWinnersCommand.php, app/controllers/WinnerController.php, app/models/User.php, app/models/Winner.php, app/routes.php, app/start/artisan.php
This PR adds a new artisan command called `transfer:winners`, which calls a new method on the `Winner` model (along with a few other methods) to transfer the winner data into the `winners` table. It handles mass updating (for data that previously wasn't added) and adding/removing new single rows of students to the `winners` table to add them as they're awarded/revoked a scholarship.
The method on the `Winner` model also does a quick check to confirm that the database has been updated via the migration, otherwise it will throw an error and stops execution.
When doing a full transfer to add all current winner data to the `Winners` table, the transfer command also ensures that the cache of winners for each scholarship is properly cleared, so it can update.
---
@angaither @sbsmith86
=> Enabling new artisan command, and adding some error handling.

app/Scholarship/Repositories/SettingRepository.php, app/assets/sass/_admin/_custom.scss, app/commands/CustomStylesCommand.php, app/controllers/admin/SettingsController.php, app/routes.php, app/views/admin/layouts/partials/subnav-settings.blade.php
Fixes #680 
Creates a `clear cache` button on the admin side panel that will allow admins to clear the cache from the UI. After the cache is cleared, we reset any custom appearance settings.
@weerd @angaither
=> Clear Cache Button

app/models/Export.php
Resolves #665 
Added `SELECT DISTINCT` to the SQL query that is getting the past recommenders because I was seeing dupes in my  dev and qa databases. The dupes were because a person could be a recommendation for multiple people.
=> Dedupe the recommender's query

app/commands/DatabaseWipeCommand.php, app/controllers/WinnerController.php, app/start/artisan.php, app/views/admin/winners/edit.blade.php, app/views/admin/winners/index.blade.php, app/views/pages/partials/_winners-gallery.blade.php
This PR creates a new Artisan command `wipe:applicants` which goes through and eliminates all the user related data for prior scholarship year's applications, while leaving all the site data and winners data intact.
Since all applicant data is getting cleared out, this PR also updates a few views and controllers to properly load the winners data that was transfered and modified in #681.
_NOTE: Once merged, we will need to run the `php artisan transfer:winners` command so that the views don't break (gallery on home page and winners pages in admin)_
---
@angaither @sbsmith86
=> New command to help wipe database of prior users.

app/views/admin/winners/index.blade.php
Fixes #687 
Appending the year that the scholarship started to the name of the scholarship in the dropdown menu on admin/winner. 
@weerd @angaither
=> Add application year to winner filter by dropdown

app/controllers/ApplicationController.php, app/controllers/StatusController.php, app/controllers/admin/AdminController.php, app/models/Scholarship.php
This PR updates `getScholarshipLabels()` to take an `$id` parameter and updates the eloquent query it uses to first select the correct scholarship based on the `$id` and grab the labels for the application for that scholarship. 
In this PR, I also update calls to `getScholarshipLabels()` to use the $id parameter to get labels for the correct scholarship.
I would start at `app/models/Scholarship.php`. This is where I update the function to take in a parameter.
Other changes are for updating calls to `getScholarshipLabels()`
go to `/application/create` and you should see the label correlating to the current active scholarship. 
Also, go to view an old users application, and you should see the labels for the scholarship they applied for at the time.
Previously, the function was always …
=> Get labels for correct scholarships.

app/models/Scholarship.php, app/views/pages/home.blade.php, app/views/pages/partials/_block_cta.blade.php
This PR adds an additional check to see if an application `isOpen()` before outputting the application cta block and the nomination block on the homepage.
In `app/models/Scholarship.php` I add a new function `isOpen()` and then use that function to check if an application is open in the other blade templates.
Create a scholarship with an application start date that is set in the future :rocket: and you should not see a "continue application" button or the nomination form on the homepage. On the flip side, set the application start and end dates to be before and after the current date, and the button and form should appear. 
#693
=> Scholarship dates

app/views/layouts/partials/navigation.blade.php
'apply' in the top nav was showing up because the scholarship was checking if closed, but not if it was open yet. 
Fixes #693
=> Don't show the apply label before scholarship is open

app/controllers/RecommendationController.php, app/views/recommendation/create.blade.php
fixes #717 
only authenticated uses can view the recommendation/create page.
Recommenders end up being authenticated users, right? If not this would end up blocking them. I tested as anonymous and logged in, but I couldn't test as a recommender because I was unable to login as one.
There is an error when admins try to view this page which was happening before and after my changes.
=> do not allow anonymous users to access recommendation/create

app/controllers/admin/AdminController.php, app/routes.php, app/views/admin/applications/show.blade.php
fixes #723 
added a button to the bottom of an application to allow admins to mark an app as complete.
if the app is currently not complete, it looks like this:
once that is clicked, if you return to the same application, it looks like this:
=> Mark app complete

app/controllers/admin/AdminController.php, app/views/admin/applications/edit.blade.php
this is essentially the same fix we made to the "show" view (https://github.com/DoSomething/longshot/pull/722)
edit view was crashing when there wasn't an app or recs
=> fix admin edit app from crashing when there isn't an app or rec

app/commands/DatabaseWipeCommand.php
fixes #735 
Older instances don't necessarily have a failed_jobs table, so now we check if the table exists before trying to truncate it. The command was crashing after it tried to truncate the table that didn't exist, which is before the admins got added back in so it was causing that issue as well.
=> fix wipe:appliants to work when there is no failed_jobs table

app/Http/Controllers/RecommendationController.php, app/Http/Controllers/StatusController.php, app/Http/Middleware/CheckIfRecRequested.php, resources/views/recommendation/applicant_edit.blade.php, resources/views/recommendation/create.blade.php, resources/views/recommendation/edit.blade.php, resources/views/status/index.blade.php
Enter the joyous world of recommendations!
StyleCI fix PR to follow after I wrap up my branches in progress, otherwise there will be one million conflicts
Important changes:
- "Add a rec" button on status page is now "add or edit a rec"
- Applicant rec edit page allows them to edit existing recs that have not been completed and request new recs
- If an applicant edits an existing rec request email address, a new email is sent. Otherwise, no new email is sent.
- Recommenders can edit their name, email, and phone number on the recommendation page
Fixes #745
Fixes #750
=> users can edit rec info

resources/views/layouts/master.blade.php
- code seemed to work fine as it was, but it didn't past the test without this additional check
=> needed to actually check if variable is empty in order to pass test

resources/views/pages/home.blade.php
```
FatalErrorException in ae334a78cf7b8e3ba140772f80c69499f5c7db4d.php line 15:
Class 'Scholarship' not found
```
- this should fix the error on the whitelabel homepage
=> access scholarship variable correctly in homepage

app/Http/Controllers/RecommendationController.php
- alpha validation does not allow spaces, which we probably do want to allow in these three fields, so I changed these fields to just be required
- this is consistent with how we validate first and last names for users
=> change first name, last name, relationship validation to allow spaces

app/Http/Controllers/admin/SettingsController.php, app/Scholarship/Repositories/SettingRepository.php, database/seeds/SettingsTableSeeder.php, resources/views/layouts/master.blade.php
- add new setting to allow admins to input the embed code and font name from Typekit
- updates to master template to change the fonts if they're there
- I used `!IMPORTANT` on the headers because they weren't updating otherwise, let me know if there is a better way
- add db seed for the new settings
- I dug around and couldn't find where in Typekit I could set the name of the font, so currently admins have to input that as well
For review: dream team of @weerd & @DFurnes 🏀 
Fixes #754
=> Custom fonts

.env.example, config/mail.php
- Many sources say the error we were getting was because we didn't have a default email address, but the email error was still happening after one was added. Maybe it says the same thing about a blank name?
- Also, the mail host was incorrect.
This is the error:
```
Swift_RfcComplianceException in MailboxHeader.php line 348:
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
```
=> maybe we need a name?

database/migrations/2016_05_31_201638_rename_password_reminders_table.php
- I accidentally left this out of the last PR
- this table is renamed to match everything else being `reset` and not `remind`
=> need to rename password_reminders to password_resets

app/Http/Controllers/admin/AdminController.php, resources/views/admin/applications/edit.blade.php, resources/views/admin/applications/show.blade.php
- We do not want to crash if a profile is not found, because that is a real case that can happen.
- Instead, let the profile be null and just make sure it's not before using it.
- Maybe it makes sense to only show the edit button if there is something editable (profile, application, or recommendations) being displayed for the applicant. I included that change. We can unchange it if we want.
- Login as an admin. 
- Go to an application that only has a registration (aka they created an account but did not fill out Basic Info). Make sure there is no edit button. 
- Go to applications that have all kinds of combinations of profiles, applications, and recs. Make sure the edit button shows up when it should and that nothing crashes when you click on it.
Fixes #817
=> fixes edit button crashes and rethink that button

app/Http/Middleware/Authenticate.php, app/Http/routes.php
If a user tries to go to the status page but isn't logged in (or anything else that causes the auth middleware to kick in), they are redirected to the homepage WITH flash messaging 💥 
On Whitelabel, click "continue an application" or go to `/status` and make sure you end up on the homepage with this message:
I couldn't get this to work for a while and I thiiiiiink it was fixed by the change to the routes file?
Fixes #820
=> flash message 

app/Http/Controllers/SessionsController.php
If you login and you're an admin you get directed to `/admin` instead of `/status`.
Login as an admin and make sure you get redirected to `/admin`. Login as a plebian and make sure you still get redirected to `/status`.
I'm sure I commented this out for a good reason 😬 , but whatever it was is not longer valid.
=> Admin redirect

app/Http/Controllers/admin/SettingsController.php
- This does the same validation changes to the metadata settings that were done previously to the other types of settings.
- Try to update any and all metadata settings and make sure there are no crashes. Also verify that the validation is happening correctly. I think all the relevant validations happening are:
```
'favicon'                     => 'mimes:ico',
'open_graph_data_url'         => 'url',
```
Fixes #825
=> update to new validation

app/Http/Controllers/NominationController.php
The `NominationController` was missing the models it uses. This adds them in!
Make sure you are able to send a nomination from the block on the homepage. If the block isn't showing up, check the timing of the scholarship and change it so that it does show up (aka start date is before today, nom end date is after today).
Fixes this:
=> add missing models to nomination controller

resources/views/layouts/partials/footer.blade.php
Don't escape the HTML in the footer text because we want to use it.
1. Put HTML in the "Footer text" field at `/admin/settings/general`.
2. Go look at the footer.
3. See your text formatted properly.
Yet again! These are hard to catch because they don't always show up locally and especially don't show up locally if you aren't trying to use markdown in that field!
Fixes #836
=> allow us to use html in the footer

gulpfile.js, package.json, resources/assets/js/slideshow.js
- Browserifies our javascript! 
- Adds new dependencies to `package.json` in order to resolve errors when browerifying.
- Puts `const` or `var` before a couple of variables in `slideshow.js` so it works and so we don't get any errors about things being undefined
Make sure the winner gallery slideshow works! You should be able to click on any tile to start and then go back and forth through all of them.
Fixes #839
=> fixing the slideshow of winners

composer.json, composer.lock
Adds redis to composer.json and includes updated composer.lock.
with Morgan's 👀 !
from @blisteringherb in Slack:
`@katie` I’ve added an env var that matches the one in Gladiator `QUEUE_DRIVER=redis`. Now I’m getting an error on Whitelabel that the Predis client isn’t found. Gladiator and Voting app have it, but longshot doesn’t. It needs `"predis/predis": "~1.0",` added to composer.
=> add redis to composer.json and include updated composer.lock

app/Http/Controllers/ApplicationController.php, app/models/Application.php
- Removes a dummy variable
- make a comment more clear
See if you think `upload` should be fillable.
The dummy variable was I think a placeholder for `upload` but we actually don't want that attribute to be fillable since we have additional logic surrounding uploading files so we don't want to just shove 'em in there.
=> remove dummy variable and leave all functionality the same

app/Http/Controllers/admin/AdminController.php
When admins re-sent rec emails:
1. The recommendation token wasn't being grabbed properly and now it is.
2. The tokens were not consistent with the other tokens for the same email.
Does it make sense to do it this way? Open to suggestions.
=> get the rec token correctly and use consistent email tokens

app/Http/Controllers/RecommendationController.php, resources/views/layouts/master.blade.php
A whole lot of good (in my opinion) things!
- when first requesting a recommendation, ALL of them will save and not just the first one
- the form does not save until there are no validation errors (I think that's okay)
- validation errors are displayed like this now (which is a huuuuge improvement):
- once the form is saved, the user is redirected to the status page (this is the same)
See if I've included enough good comments and if this approach makes sense in general
=> Fix mass rec creation

resources/assets/js/form-loader.js, resources/assets/js/main.js
JS city!
Adds JS to change form submit buttons to `readonly` once they are clicked once. This will allow their values to still be passed while being essentially `disabled` aka we get all the info we need, but users can't click them again.
Check that I included everything necessary for JS land.
We think forms being submitted on top of themselves is the root of the CSRF Token Mismatch errors we are seeing so hopefully this will fix that.
=> make form submit buttons readonly after click

app/Http/Controllers/ApplicationController.php, app/Http/Controllers/NominationController.php, app/Http/Controllers/ProfilesController.php, app/Http/Controllers/RecommendationController.php, app/Http/Controllers/RegistrationController.php, app/Http/Middleware/CheckIfCurrentUser.php
- Adds index functions on almost everything that redirect to the homepage. We are getting errors from users hitting these routes that don't really exist. Hopefully with the submit button going `readonly` after 1 click people won't be hitting them anymore, but just in case let's not get errors.
- Fixes some middleware/access logic (like if they need to be logged in let's redirect them to the login page instead of the homepage)
- On some models (application, profile, recommendation), the `show` route was being hit. For application and profile, we redirect the user to the edit page if there is a model for that id (and then the edit function takes care of making sure that the id in the url and that user's id are the same). If not, we direct them to the edit page. For recommendation, we need …
=> handle users hitting routes that we don't really use

app/Exceptions/Handler.php
If a user gets a `TokenMismatchException`, redirect them back to the page they were on with a red message that says `There was an error processing your submission, please try again.` This way an applicant will not lose all of the data they had entered. If their session really has ended, that data would be lost anyway and they should end up with a message asking them to login.
Test 1:
I manually threw some token mismatch exceptions on controller functions that get hit when saving forms to mimic what has been happening to some users. I was properly redirected back to the form with all my entries still there and with the flash message.
Test 2:
Additionally, I manually logged out the user after the mismatch was caught to make sure they are properly redirected to a page that asks them to login …
=> handle token mismatches

resources/views/admin/applications/show.blade.php, resources/views/application/partials/_form_application.blade.php
Allow admins to use HTML in editable questions so they can put cool links like this:
Does HTML in these fields show up right?
I noticed on CAPS there was some markdown in these fields that wasn't showing up right.
Fixes #868
=> allow html in editable application questions

app/Http/Controllers/ApplicationController.php, resources/views/application/partials/_form_application.blade.php
Adds two new test type options to the test dropdown on the application, `SAT (Out of 1600)` and `SAT (Out of 2400)`. This way, admins can tell which test the student took if they have an ambiguous score like `1500`. This also updated the validation to force applicants to input a numerical score if they have selected either one of these options.
Can you successfully choose either of these options? Do you get a validation error if you select one of these options but don't input a score?
Pivotal [card](https://www.pivotaltracker.com/story/show/150027511)
=> Add new SAT test type options

app/Http/Controllers/admin/AdminController.php, app/models/Export.php
When sending emails to groups, we were trying to grab the `email` from each row of the query made to construct the group. However, when dealing with nominations nothing is stored as `email` since there are two emails: the nominator email and the nominee email.
The queries to get the nominators and the nominees are [here](https://github.com/DoSomething/longshot/blob/master/app/models/Export.php#L80-L94).
Since in the query, the emails are grabbed `as Email`, I added a check to grab `Email` if `email` is not set. I also updated the `nominated_no_app_query` to grab the nominee email address as `Email` so I didn't have to make a third check for `nom_email`.
Would we be able to successfully grab the email from each query in [Export.php](https://github.com/DoSomething/longshot/blob/master/app/mo …
=> Fixes bug where emails to people involved with nominations did not work

app/Http/Controllers/ApplicationController.php, app/Http/Controllers/admin/ScholarshipController.php, database/migrations/2017_08_31_144335_add_image_uploads_column_to_scholarships_table.php, resources/views/admin/scholarship/partials/_form_scholarship.blade.php, resources/views/application/partials/_form_application.blade.php
- Display a "Allow applicants to upload images?" checkbox to admins on the edit scholarship page
- Adds a migration to add a new column `image_uploads` to the `scholarships` table. This will store whether or not the checkbox was checked.
- Fixes the way the other checkbox on the edit scholarship page was being displayed as checked or not (this was not working)
- Conditionally display the photo uploader to the user. This does not impact validation because it is already an optional field.
Is the migration valid? Will the checkboxes work as expected?
Currently only one scholarship uses the image uploader, so we want to make it optional.
[Pivotal card
](https://www.pivotaltracker.com/story/show/150058487)
=> Allow admins to toggle ability for applicants to upload photos

app/Http/Controllers/admin/AdminController.php, app/models/Export.php, resources/views/admin/reports/export.blade.php
1. Fixes a bug where admins couldn't edit applications
2. Adds 3 new queries:
- one for just demographic data for all users
- one for ALL data for users rated as "yes" by admins
- one for ALL data for ALL users
3. Adds 3 new buttons to the export page for these exports
4. Links to the [corresponding wiki page](https://github.com/DoSomething/longshot/wiki/Group-Emails-and-CSV-Exports-(Admin)) from the exports page
Export page now looks like this:
Two of these queries are monsters but they have been working for me. Did I make a silly error in the queries? Does the exports page look okay?
If the admins can get all the data into excel, they have more flexibility to manipulate it. As usual, let me know if you have ANY questions 😺 
[Pivotal card …
=> Add 3 new exports

resources/views/admin/scholarship/partials/_form_scholarship.blade.php
On the form to create or edit a scholarship, we now check if the scholarship exists (aka if the form is to create or edit a scholarship) before trying to use values from the scholarship. In this case, we are seeing if 2 boxes should be checked. If the scholarship doesn't exist yet, don't check the boxes. Otherwise, check them based on how they are set in the scholarship.
Does this do what I said it would?
I introduced this bug in https://github.com/DoSomething/longshot/pull/881
=> Don't check boxes if scholarship not created yet

app/Http/Controllers/ApplicationController.php, app/Http/Controllers/ProfilesController.php, resources/views/admin/scholarship/partials/_form_scholarship.blade.php
This fixes a bug that I was not able to duplicate until recently. In some cases, there were duplicate applications for users. I found that the profiles can also be duplicated, but that is not as obvious unless you are looking at the database.
Duplication happened when the following took place:
1. A user starts working on their profile or application (from the `/create` page)
2. The user clicks "save as draft" and is sent to the `/edit` page
3. The user goes back in their browser
4. The user makes more updates to the form and submits again
5. BOOM two copies! Maybe more depending on how many times you did that!
The fixes:
1. If a user hits `/create` and they already have an application or profile, redirect them to the edit page.
2. If a user DOES go back to `/create` in their browser (in …
=> Never let there be duplicate profiles or applications

app/models/Scholarship.php
There was a flaw in the `isClosed()` logic. We were correctly checking if the current date was AFTER the application end date, but not it if it was before the application start date. Any nominations or accounts must be created after the start date but before the end date.
Scholarships are only open if:
`date_has_expired($end_date) || !date_has_expired($start_date);`
The `$end_date` has not yet happened or the `$start_date` has already happened.
Does this logic make sense for before the start date, between the start date and the end date, and after the end date?
I think normally this wasn't a problem because we always grabbed the `currentScholarship` but if somehow we end up caching the newest one before the start date, then we need to check on the start date.
[Pivotal …
=> Fix `isClosed()` logic on Scholarships

resources/views/admin/scholarship/partials/_form_scholarship.blade.php
Fixes an error where as the GPA on the scholarship, we were saving the array index instead of the value. So if the 6th GPA in the list was selected (3.5) from the dropdown, it was saved instead as its index (5). When we check if applications submitted had GPAs that were too low, we were comparing to the wrong number (5 instead of 3.5 in this example).
Will this form save the expected GPA value?
[Pivotal card](https://www.pivotaltracker.com/story/show/151532563)
=> Fix bug where gpa_min is not stored correctly

database/migrations/2017_11_14_170801_add_index_on_profile_id_to_races_table.php
Adds an index on `profile_id` to the `races` table so that queries that use this table will be faster!
Does this index make sense?
I think this is what was making CSV downloads so slow!
[Pivotal card](https://www.pivotaltracker.com/story/show/152475544)
=> Add index on profile_id to races table

.editorconfig, .styleci.yml
I think previously our StyleCI settings were either not customized or lived in StyleCI itself and were lost. Never had an `.editorconfig` and no time like the present 🎁 
👀 
StyleCI wasn't running and so I stole the settings from Rogue since it is running again.
=> Add .styleci.yml and .editorconfig

resources/views/application/partials/_form_application.blade.php
Fixes an error where the `@endif` for the fifth extra question is not after the fifth question, but after a whole bunch of questions!
This caused a bunch of questions to not be displayed unless the fifth extra optional question was used as well.
Is the `@endif` in the right place now?
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/150050426)
=> Put that @endif in the right place

app/Http/Controllers/ApplicationController.php, app/Http/Controllers/admin/AdminController.php, composer.json, composer.lock
📁 Instead of doing it ourselves, use [`league/csv`](https://csv.thephpleague.com/) to build the CSV files that we make available for download. I'm hoping this change will take care of the weird truncated files that we've been seeing, but we'll see! In order to make this change, we need to get the query results as an array of arrays (previously we were getting an array of objects) and the only way (after much research) I found to do this without iterating through everything was `json_decode(json_encode($query_result), true)`.  
- If we wanted to, we _could_ iterate through each result, cast it as an array, and use `insertOne` instead of [`insertAll`](https://github.com/thephpleague/csv/blob/312762d63e1e66337ad02c9b717611a28f08d919/src/Writer.php#L98-L113) (`insertAll` just iterates through …
=> Using league/csv and better logging

app/Console/Commands/GenerateTestData.php, app/Console/Kernel.php, database/factories/ModelFactory.php
:weight_lifting_woman: Add a bunch of model factories to create the fake data in finished and partially finished states.
✍️ Adds an artisan command to create all or one type of data. If run with no arguments, creates 1 of each option. Otherwise, creates the specified number of the given type (or everything if no type given). The command uses the factories to create the data and relates them in different ways given the scenario. The different types are:
- plain user  - `user`
- user with partial profile (including race) - `partial-profile-race`
- user with partial profile (no race) - `partial-profile`
- user with partial profile and partial app (no race) - `partial-profile-and-app`
- user with partial profile and partial app (including race) - `partial-profile-and-app-race`
- user with …
=> Add command to easily generate a bunch of fake data

config/app.php
Removes the placeholder key! In the event that we do not set `APP_KEY` in the `.env` file, we would rather get errors and fix it than use a key that is public.
👀
=> Remove placeholder key

app/Http/Controllers/RecommendationController.php
When displaying the form to add/edit recommendations to applicants, don't just check for the application id and then show the form! Also check that the logged in user is the owner of that application, and THEN show the form.
If an applicant tries to view a recommendation form that isn't theirs, redirect to the home page with a "You are not authorized to view that page." message.
Does this keep applicant's eyes on their own forms? Does it accidentally block anyone from seeing something that they should be able to see?
[Card](https://www.pivotaltracker.com/story/show/154723362)
=> Only let users fill out their own recommendation form

.styleci.yml, app/Http/Controllers/admin/AdminController.php, app/Jobs/Job.php, app/Jobs/SendGroupEmail.php, config/app.php
This adds a Laravel job to handle the sending of group emails in the background. Now, when an admin sends a group email, all that has to happen in realtime is telling the job which category of group email we are sending! We also include the email address of the admin and notify them via email once the job has processed all of the group emails. None of the logic of sending the group emails has changed here, it just happens in a different place now.
Wasn't sure the best way to notify admins that the emails are ready to be sent. I updated the flash message to say `We will send an email to everyone!` (instead of saying that we did). Once the job builds all the emails and calls `sendEmail` on them, the admin gets an email telling them that the emails have all been queued. But at that point, …
=> Send group emails in the background

database/migrations/2018_09_11_170552_create_failed_jobs_table.php
This adds a failed jobs table to the database so we can keep track of emails that fail to be sent. Adding this table fixed the issue with sending emails on the production Footlocker server after going through the steps listed here - https://laravel.com/docs/5.7/queues#running-the-queue-worker
https://github.com/DoSomething/devops/issues/441
=> Adding failed jobs table migration

composer.json, composer.lock
This pull request updates Longshot to PHP 7.1, because it's the lowest version of PHP that's supported by Heroku's 2018 stack! Yowza.
👀
Fixes #
=> Update to PHP 7.1 for Heroku.

app/Scholarship/Repositories/SettingRepository.php, app/Scholarship/helpers.php, resources/views/admin/settings/partials/_form_settings.blade.php
Whoops! Forgot to import the `Storage` facade in #917, so this was erroring out:
> Nov 16 16:16:30 dosomething-longshot-qa app/web.1:  [16-Nov-2018 21:16:30 UTC] [2018-11-16 21:16:30] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Scholarship\Repositories\Storage' not found in /app/app/Scholarship/Repositories/SettingRepository.php:88 
I also double-checked [the documentation](https://laravel.com/docs/5.2/filesystem#basic-usage) and realized I had been using `Storage::put` incorrectly (by passing the "file" object instead of contents as a string). Finally, this PR uses the `asset_url` helper to display these images in the admin panel too!
👀 
N/A
=> Fix some bugs with uploading images to S3.

Procfile, public/.user.ini
We want the New Relic agent to be included in this application's builds, since those get promoted between environments (and so if it doesn't exist in QA, it'd never exist in production). However, if we don't disable the New Relic agent on production, we'll get drowned in alerting! Oy!
This pull request sets `newrelic.enabled` based on the `$NEW_RELIC_ENABLED` enviroment variable so we can selectively enable or disable this in different environments, and updates the command for the queue process to read this INI file too. I've tested this alongside DoSomething/infrastructure#59 on Longshot QA & all seems well – next step is testing on prod!
👀
Once this is sorted out, I'll clean up how we handle this in other apps as well.
=> Add a configuration setting for enabling/disabling New Relic.

app/Http/Controllers/ApplicationController.php
This should fix up [these issues](https://dosomething.slack.com/archives/C03T8SDMW/p1548253590017300?thread_ts=1548195989.014800&cid=C03T8SDMW) where the `$user` variable in the "update application" route was undefined, and so users were unable to upload files to an existing app.
👀
🆙 
References [this Slack conversation](https://dosomething.slack.com/archives/C03T8SDMW/p1548253590017300?thread_ts=1548195989.014800&cid=C03T8SDMW).
=> Fix issue with undefined variable $user.

package.json
This pull request fixes builds for this application, which were [failing](https://dashboard.heroku.com/apps/longshot-qa/activity/builds/ad305580-60e1-4a39-9c9a-6738986ff585) because of an issue with Gulp introduced in Node 10.15.0. By pinning to the [previously working](https://dashboard.heroku.com/apps/longshot-qa/activity/builds/69196f81-a52b-4b2a-a7cf-af631bebaa7f) Node LTS version (10.14.1), builds [are back to "green"](https://dashboard.heroku.com/apps/longshot-qa/activity/releases/80354e64-a251-4429-9323-4673717a735e).
Follow the links to see the builds before and after this quick fix.
We should update the tooling in this application, since its Bower + Gulp toolchain is outdated and not something we use or support on any of our other applications.
N/A
=> Lock Node to known working version.

app/Console/Commands/DatabaseWipeCommand.php, database/migrations/2014_09_24_151910_add_complete_field.php, database/migrations/2014_10_02_135113_update-status-on-app.php
This includes a complete refactoring of the `wipe:applicants` command to hopefully address all the issues we've been seeing with it.
🔢 It now calls `delete()` instead of `truncate()` on the tables, which wipes all data from the tables while preserving the `auto_increment`. This update helps us to avoid conflicts and was also part of the issues we were seeing with admins. This change also allows us to avoid manually changing and SQL settings in code.
🚔 Use a new method to preserve admins. Previously we saved the admin users, wiped the database, and re-created the admin users. Without preserving the `auto_increment`, this also meant that the `user_id` column in the `role_user` table did not necessarily match with the new admin user `id`s. NOW we use a more specific query and only delete …
=> Fix `wipe:applicants` command to preserve admins and auto_increment

app/Http/Controllers/PagesController.php
🖼 When saving images on Pages, we weren't using the `Storage` facade but on the front end we pull from `Storage`. So, the frontend looks in S3 and does not find the image there. I've tried to update the `page` model to store in S3 and from what I can tell it works locally, but locally I'm not able to actually store on S3 so I can't be sure.
Will this work when connected to S3?
Issues noticed on Footlocker Internal!
🤠
=> Use storage facade for images on "pages"

app/Http/Controllers/PagesController.php
📶 Make sure to save the full storage path of the image being uploaded. Otherwise it will not include `content/` which is where the file will actually live!
🌽 Do not grab and add the extension to the path, because it will already be there!
Will the actual file path and the path in the database match?
Got partway there last time!
🤠
=> Fix uploads for Pages to store right path

app/Http/Controllers/WinnerController.php
This pull request uses `Storage::put` to upload images of winners, rather than explicitly "moving" the file on the disk. This allows us to use S3 to host this image on production.
👀
Unblocks an issue with Footlocker's external scholarship.
Fixes https://github.com/DoSomething/longshot/issues/937
=> Upload winner images to S3, if using that driver.
